const list = [
    {
      id: 1,
      title: "Apple iPhone 12 Pro",
      author: "BLACK",
      price: 60000,
      img: "https://m.media-amazon.com/images/I/71MHTD3uL4L.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "realme",
      author: "BLUE",
      price: 45000,
      img: "https://www.vhv.rs/dpng/d/572-5725669_realme-png-image-realme-2-pro-4gb-ram.png",
      amount: 1,
    },
    {
      id: 3,
      title: "Redmi Note 10S",
      author: "BLACK",
      price: 28000,
      img: "https://cdn.bajajelectronics.com/product/7375-1.png",
      amount: 1,
    },
    {
      id: 4,
      title: "smartwatch",
      author: "SILVER AND BLACK",
      price: 1500,
      img: "https://cdn.vox-cdn.com/thumbor/P7a-prS4XSR2T-_inQS9B8pMMY4=/1400x1050/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22889772/amazon_halo_view.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "camera",
      author: "BLACK",
      price: 50000,
      img: "https://m.media-amazon.com/images/I/71imR8TIR7L._AC_SX355_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "wireless bluetooth ",
      author: "BOAT BLACK",
      price: 2000,
      img: "https://m.media-amazon.com/images/I/714azwTIF+L._AC_SY355_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "HP ",
      author: "BLACK",
      price: 69000,
      img: "https://purepng.com/public/uploads/large/purepng.com-laptopelectronicslaptopcomputer-941524676379zuw2c.png",
      amount: 1,
    },
    {
      id: 8,
      title: "MACBOOK",
      author: "SILVER",
      price: 89000,
      img: "https://pngimg.com/uploads/macbook/macbook_PNG65.png",
      amount: 1,
    },
    {
      id: 9,
      title: "DELL ",
      author: "BLACK",
      price: 55000,
      img: "https://images-eu.ssl-images-amazon.com/images/I/416c9Lgnt7L._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_PIStarRatingONEANDHALF%2CBottomLeft%2C360%2C-6_SR600%2C315_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Girl-Dress",
      author: "WHITE RED FLOWER",
      price: 860,
      img: "https://www.vhv.rs/dpng/d/542-5426773_girl-dress-girl-hd-png-download.png",
      amount: 1,
    },
    {
      id: 11,
      title: "Watch",
      author: "SILVER",
      price: 5000,
      img: "https://img.favpng.com/22/19/25/fr-d-rique-constant-watch-clock-strap-clothing-accessories-png-favpng-MS50de9PRBdxZxFp5ae2fUXQm.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Men Shoes",
      author: "white and blue",
      price: 3500,
      img: "https://m.media-amazon.com/images/I/71uvBGzZCPL._AC_UL320_.jpg",
      amount: 1,
    },
  ];
  
  export default list;